### ISSUE TITLE
Don't strip whitespace on scope?

### ISSUE THREAD

**Issue by MikeMcQuaid** [bomberstudios/Strip-Whitespace-On-Save.tmbundle#15]
Hi! Thanks for the great bundle, I use it daily ❤️ 

I'm wondering it's possible to avoid stripping whitespace only on specific scopes e.g. after a Ruby `__END__` block. In case you're wondering: Homebrew uses these for patches and I'm trying to avoid stripping whitespace only on the patch while still doing so on the Ruby.

Feel free to immediately close as this is a question rather than a problem.

Thanks again!

**Comment by bomberstudios** [comment]
I was going to say that it should be possible already (check https://github.com/bomberstudios/Strip-Whitespace-On-Save.tmbundle#without-using-tm_properties) and to use something like `source.ruby text.plain` for a scope, but then I realised that the bundle is basically replacing the whole document, so it would still remove whitespaces…

A different approach would be to simply disable the bundle for anything stored in the Homebrew folder, using `.tm_properties`:

```
[ "/usr/local/Homebrew/Library/Taps/**/*" ]
scopeAttributes = attr.keep-whitespace
```

(Haven't checked the syntax, so you may have to do some massaging to make sure it works)

Hope it helps!

**Comment by MikeMcQuaid** [comment]
Thanks @bomberstudios. 

> I realised that the bundle is basically replacing the whole document, so it would still remove whitespaces…

Yeh, I think this is going to make this not workable. Thanks anyway ❤️
